### ISSUE TITLE
Question: browserslist support

### ISSUE THREAD

**Issue by Conaclos** [developit/microbundle#455] opened 2019-07-22 21:52 UTC
Is there any plan to support [browserlist](https://github.com/browserslist/browserslist)?

For instance, the next "browserlist":

```json
"browserslist": [
    "maintained node versions"
]
```

could transpile the source-code in ES2015 for the *main* target.

**Comment by developit** [comment] 2019-07-29 18:50
It's not possible to reliably determine Terser settings for a given browserslist configuration, so I'm not sure how this could be achieved.

For Node usage I could see potentially having an option to specify node version, or even just bake "maintained node versions" in as a default. However, browser usage is much less clear to me - would the package just state that it doesn't run in 5% of browsers?

**Comment by Conaclos** [comment] 2019-08-01 11:40
We could rely on the [`engines` property][engines] of `package.json` to determine the supported node versions.

[engines]: https://docs.npmjs.com/files/package.json#engines

**Comment by simnalamburt** [comment] 2020-08-06 16:23
Now [README](https://github.com/developit/microbundle/blob/5881387/README.md) says it supports browserslist. Can we close this issue now?

**Comment by ydennisy** [comment] 2020-11-30 09:48
Does microbundle support browserslist? From a quick test it does not seem too.

**Comment by developit** [comment] 2020-12-02 02:34
It does support browserslist. We use it to determine the syntax level for the UMD, ESM and CJS outputs. It is ignored for the modern output by design. 

How were you testing?

**Closed** 2020-12-18 21:23 UTC
Labels: enhancement :rocket:, question :grey_question:
