### ISSUE TITLE
microbundle --no-compress removes the first line if it is a comment

### ISSUE THREAD

**Issue by trafnar** [developit/microbundle#869] opened 2021-07-21 21:02 UTC
I set up a simple project and needed to maintain comments, so I used the `--no-compress` flag, which worked, except it seems to remove the first line if it is a comment.

```typescript
// foo
// bar
console.log("Hello")
```

becomes this in `dist/index.js`

```javascript
//bar
console.log("Hello")
```

I'm using typescript with this configuration in package.json:
```json
{
  "main": "dist/index.js",
  "scripts": {
    "build": "microbundle --no-compress",
    "dev": "microbundle --no-compress watch"
  },
  "source": "src/index.ts",
  "devDependencies": {
    "microbundle": "^0.13.0"
  }
}
```

**Comment by developit** [comment] 2021-07-21 21:08
hah! what a strange issue. I'm guessing this is a Terser bug.

**Comment by rschristian** [comment] 2021-07-21 21:21
Shouldn't be Terser, it isn't used with compression disabled.

https://github.com/developit/microbundle/blob/b1a637486234a2ae784ccf0c512321e2d3efef7c/src/index.js#L574-L575

**Comment by rschristian** [comment] 2022-04-25 04:52
This might've been an upstream bug, as I cannot reproduce on latest version (`0.14.2`). Therefore going to close this out.

**Closed by rschristian** 2022-04-25 04:52 UTC
