### ISSUE TITLE
Add support for css preprocessors

### ISSUE THREAD

**Issue by BadMask121** [developit/microbundle#699] opened 2020-08-16 15:33 UTC
Currently my scss files get compiled to css, I suggest there should be an option to turn off css bundling and support other css preprocessor

**Comment by wardpeet** [comment] 2020-08-16 15:42
Hey, thank you for opening this issue. Why would you want to keep preprocess css? Microbundle is opinionated to compile everything away into css & javascript bundles. If you're looking for a different use case we suggest using rollup or any other bundler.

**Comment by BadMask121** [comment] 2020-08-16 16:23
@wardpeet thanks for the reply, by that doesn't work for my use case, ill explain

I have typescript a react component

```
import React from "react";
import { ReactComponent as Attachment } from "./assets/file-text.svg";
import "./style.scss";

interface IAttachment {
	text: string | React.ReactElement;
	style?: React.CSSProperties;
	fontSize?: string;
}
export default ({ text }: IAttachment) => {
	return (
		<p className="hello" >
			<Attachment /> &nbsp;
			{text}
		</p>
	);
};
```

and a style.scss file

```
.hello{
    color: blue;
}
```

building the component process the .scss file to index.scss contains the following: 

```
._RB1TF {
  color: blue; }
```

the issue is when testing the component when inspected on the browser the className property remains as `hello` and not the processed classname, therefore not changing the color to blue as specified on the .scss file

**Comment by BadMask121** [comment] 2020-08-16 16:45
I believe the processed index.css file is not being required inside the build file `index.moden.js` and also the build is not changing the classname inside build file @adrienpoly

**Comment by developit** [comment] 2020-08-16 19:33
Hi - this is [CSS Modules](https://github.com/developit/microbundle#using-css-modules), and is working as designed. You can turn it off by passing `--css-modules false` to Microbundle.

If you're still seeing this behavior with `--css-modules false`, it's likely #653. There's a bugfix for that going out shortly (though I can't speak to when that will arrive in `microbundle-crl`).

**Comment by developit** [comment] 2020-08-16 19:33
I'm going to close this one out since it's either working-as-designed or a duplicate of #653.

**Closed by developit** 2020-08-16 19:33 UTC
