### ISSUE TITLE
build fails when vscode is open

### ISSUE THREAD

**Issue by hatemhosny** [developit/microbundle#620] opened 2020-05-20 12:31 UTC
At first, thank you for the great work 👍

when I run (from vs code terminal):
``` sh
microbundle watch src/index.ts -o demo/scripts -f umd
```

I "sometimes" get this error:
```
(rpt2 plugin) Error: EPERM: operation not permitted, rename './node_modules/.cache/.rts2_cache_umd/rpt2_e47eef70c0fc688e9eeab1b3c512de3a77e8ab47/syntacticDiagnostics/cache_' -> './node_modules/.cache/.rts2_cache_umd/rpt2_e47eef70c0fc688e9eeab1b3c512de3a77e8ab47/syntacticDiagnostics/cache'
```
This does not happen all the time.
I do not get it if I close vs code and run it from the terminal. 
I am running vs code as administrator.

I believe this is something related to vs code locking node_modules in typescript projects
https://github.com/microsoft/vscode/issues/28593
But as far as I see, there is no current active effort there to correct this.

I think we can get rid of this if we move the cache directory outside node_modules. Is that possible?

#### Environment 
vs code: 1.45.1 (user setup)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

#### Versions
- "microbundle": "^0.12.0",
- "typescript": "^3.5.3"

Thank you

**Comment by developit** [comment] 2020-05-28 22:47
@hatemhosny any chance this issue goes away when you add an ignore to your tsconfig?

```jsonc
{
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by hatemhosny** [comment] 2020-05-29 02:59
I already have 'node_modules' excluded in tsconfig.

This error still occurs frequently. It sometimes keeps occurring till I manually delete 'node_modules/.cache'

**Comment by wardpeet** [comment] 2020-08-16 19:45
@hatemhosny could you share a reproduction? I'm on windows and I cannot reproduce it.

**Comment by marvinhagemeister** [comment] 2020-12-18 21:49
Closing, since there is no reproduction.

**Closed by marvinhagemeister** 2020-12-18 21:49 UTC
Labels: needs more info

**Comment by Stan-Stani** [comment] 2023-10-10 15:14
I too have this issue. I'm unsure how I would share a reproduction when it's an intermittent error like this. Any tips?

**Comment by rschristian** [comment] 2023-10-10 15:56
`microbundle-crl` is an unmaintained fork that can be [found here](https://github.com/transitive-bullshit/microbundle).

Please check if you can reproduce with `microbundle` proper, but it looks to be a file permission issue which would be on your side. You (oddly) might not have full permissions for the directory?

**Comment by Stan-Stani** [comment] 2023-10-18 15:47
For my specific issue, and any readers in the future, I have found that  Windows Defender's MsSense.exe momentarily locks the new files and thus prevents them from being renamed.
