### ISSUE TITLE
Option --css inline produces no css

### ISSUE THREAD

**Issue by everdimension** [developit/microbundle#1052] opened 2023-07-03 17:56 UTC
Hi!

I'm using an import from a css module in my `.ts` file.

By default, imported css gets bundled into a single `lib/index.css` file. All good here.

But I pass `--css inline` option to microbundle, no css seems to be bundled at all. I do not see any css in the output js files nor in separate files.

Also I have to mention that the wording in the docs that describe the behavior of this option is quite confusing:
https://github.com/developit/microbundle/blob/ef8376ee9076b2f56aca42fd9e4c8fd4dcaf8fd0/README.md#L238-L247

From the description above, I can't really understand what "inlining" means. The word itself implies that the css would be part of the output js file.

But the example in the docs implies that there will be a separate .css file that shares a name with the js file.

What should be the expected behavior?

**Comment by rschristian** [comment] 2023-07-03 18:46
Inlining is to inject your CSS file into your JS bundle as a string.

If you aren't seeing it, it's likely due to not following the example we list or not actually consuming the CSS string (Microbundle will strip out unused values).

```js
import styles from './styles.css';
```

**Comment by everdimension** [comment] 2023-07-03 18:57
Hey, thanks for a quick reply!

> I'm not quite sure where you're getting that from, are you mixing different parts of the docs perhaps?

Confusion comes from the example you have provided:
```js
// with `microbundle --css inline`:
import css from './foo.css';
console.log(css); // the generated minified stylesheet
```

Here, I am not sure if `import css from './foo.css';` is meant to demonstrate the consumer code or the source code of the package.

The source code _does_ consume the css file. I assume otherwise I wouldn't see an output `.css` file at all.
The source code imports the file (`import s from './style.module.css'`) and accesses it's property (`className={s.propName}` in jsx)

**Comment by rschristian** [comment] 2023-07-03 19:04
> Here, I am not sure if import css from './foo.css'; is meant to demonstrate the consumer code or the source code of the package.

Source, I believe all of the examples on our docs are source FWIW.

CSS Modules and CSS inlining are mutually exclusive, hence being an option on the same flag. Inlining will inject it as a string (can't continue to use it as an object) and you'll need to handle dealing with it (likely creating a style tag, inserting the CSS, and then appending the tag to the DOM).

**Comment by hbroer** [comment] 2023-07-04 07:33
Inlining CSS ist AFAIK only usefull when writing WebComponents where You put all your styles in a <style> tag. For everything else css modules is the way top go. Just my opinion.


my-component.css:
```css
:host {
  all: initial;
}
```
my-component.ts
```ts
import css from './my-component.css';

class MyComponent extends HTMLElement {
    constructor() {
        super();
        this.attachShadow("open");
        
        const el = document.createElement("style");
        el.textContent = css;
        this.shadowDom.append(el);
    }
}
```

this will inline to:

```ts
class MyComponent extends HTMLElement {
    constructor() {
        super();
        this.attachShadow("open");
        
        const el = document.createElement("style");
        el.textContent = ":host{all:initial}";
        this.shadowDom.append(el);
    }
}
```

You can also import multiple files and join them:

```
import globalStyles from './global.css';
import componentStyles from './my-component.css'; 

class MyComponent extends HTMLElement {
    constructor() {
        ...
        el.textContent = globalStyles  + componentStyles;
        ...
    }
}
```

I used the feature here:
https://github.com/owja/micro


What it not does is what webpack can do. It does NOT add javascript which then adds a style element in the background to the DOM and inserts the styles. If you want that, you need to add your own logic. But I would not do it for some reasons, espeacialy because then your lib comes with a big side effect. If your lib relies on global css and is not a WebComponent, then it should be on the consumer to add the styles the way he/she it needs it in their environment. Then a separate css is the way to go.

**Comment by rschristian** [comment] 2023-07-04 07:40
The CSS inlining option exists only to support environments in which a consumer might not have any method of consuming CSS directly, leaving it up to the component itself to mount to the page. That certainly could be a web component, but usually they too have methods of consuming / referencing CSS through a build toolchain.

Inlining is not encouraged by any means, as it massively increases the cost of loading that CSS, due to the inherent overhead of how browsers handle JS. It's there as a last-ditch option, for when you need to take that perf and bundle hit as the styles won't make it to the consumer in any other way.

**Comment by rschristian** [comment] 2023-08-03 21:06
I'm going to close this out as, for now, it's working as intended. CSS Modules and inlining don't necessarily need to be mutually exclusive, but for Microbundle at the moment, they are.

**Closed by rschristian** 2023-08-03 21:06 UTC
