### ISSUE TITLE
Error when using file JS built by microbundle "Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by yenle16** [developit/microbundle#1078] opened 2024-04-26 01:38 UTC
Hi, This is part of my package.json to use microbundle build 1 preact widget
```
  "source": "src/index.ts",
  "main": "dist/index.js",
  "module": "dist/index.module.js",
  "umd:main": "dist/index.umd.js",
  "scripts": {
    "dev": "preact watch",
    "build:widget": "microbundle build --css inline --format cjs --no-sourcemap",
    "build:lib": "microbundle build -i src/component.js --sourcemap=false",
    "lint": "eslint '{src,test}/**/*.js'",
    "test": "jest"
  },
```
As a result, I get an index.js file in the dist folder, I use it to embed my page with a script tag
`    <script type="module" id="embed-form" src="/dist/index.js"></script>`

Browser console error '(Uncaught ReferenceError: require is not defined)'
Do you have a solution for that ?

**Comment by rschristian** [comment] 2024-04-26 02:49
Hey, thanks for popping over here, it's a bit easier to answer in full.

As mentioned, CJS is not suitable for browser use. You want the UMD, ESM, or Modern bundles for this.

I can write you up a demo application real quick, but one question: do you intend to bundle Preact with your widget (so that it can be deployed anywhere without any setup), or will you want users to bring their own copy of Preact?

**Comment by yenle16** [comment] 2024-04-26 03:39
Thank you, maybe I have solved the above error, but there is another problem I have, I am using .env variables and the current browser cannot read it 'Uncaught ReferenceError: process is not defined'
Maybe it's a mistake in setting up my build, do you know why?

**Comment by rschristian** [comment] 2024-04-26 04:46
Indeed. `process` too only exists in Node, so if you want Microbundle to swap our your variables, you need to tell it to do so with the `--define` flag. For example:

```js
// input
console.log(process.env.MY_VAR);
```

`$ microbundle --define process.env.MY_VAR="hello world!"`

```js
// output
console.log("hello world!");
```

**Comment by yenle16** [comment] 2024-04-26 04:57
Really, I think environment variables should be bind

**Comment by rschristian** [comment] 2024-04-26 05:03
I don't really have much of an opinion either way, but this is the way env vars work for now anyways.

Did you follow the example I gave for importing CSS? I'll need more to go on as, as my demo shows, it's working as intended.

**Comment by rschristian** [comment] 2024-04-26 05:42
Are you importing your built Tailwind CSS like `import styles from './built-tailwind.css'`? We won't compile your Tailwind for you, so that needs to be available before Microbundle runs.

Additionally, Tailwind produces quite large outputs, keep in mind that this will bloat your bundles by a non-negligible amount.

**Comment by yenle16** [comment] 2024-04-26 07:39
I use Tailwind to css, and when I build and use it but my tailwind classes don't work, Do you have a solution for that ?
![image](https://github.com/developit/microbundle/assets/92104643/1ae08a04-26ed-4dfa-bcc1-0eac78421bdf)

**Comment by rschristian** [comment] 2024-04-26 07:42
You need to provide a reproduction, "my tailwind classes don't work" isn't enough information for me to offer any help.

Are you creating a `<style>` tag w/ your CSS string? Are you inserting it into the document?

**Comment by yenle16** [comment] 2024-04-26 08:18
It's hard for you if I keep asking around, this is my repo and everything I configure is here, you can see how I'm doing
[https://github.com/yenle16/demo__signupform](url)

**Comment by rschristian** [comment] 2024-04-26 08:20
[This](https://github.com/yenle16/demo__signupform/blob/77582b17b802ab6f5944d8d8647e35758933e7be/src/index.ts#L4) won't work. You need to do it as I've done.

**Comment by yenle16** [comment] 2024-04-26 09:36
I can't import styles as you've done, I just can import './style.css'
![image](https://github.com/developit/microbundle/assets/92104643/bd79a837-6c7a-4f85-a7c9-52184597680c)

**Comment by rschristian** [comment] 2024-04-26 09:40
That's just TypeScript, you can ignore it with a `// @ts-ignore` comment like this:

```js
// @ts-ignore
import styles from './style.css';
```

or add an ambient declaration file like this:

```ts
// src/global.d.ts
declare module '*.css' {
	const url: string;
	export default url;
}
```

Totally unrelated to Microbundle.

**Comment by yenle16** [comment] 2024-05-17 04:23
> Indeed. `process` too only exists in Node, so if you want Microbundle to swap our your variables, you need to tell it to do so with the `--define` flag. For example:
> 
> ```js
> // input
> console.log(process.env.MY_VAR);
> ```
> 
> `$ microbundle --define process.env.MY_VAR="hello world!"`
> 
> ```js
> // output
> console.log("hello world!");
> ```

Can you help me with this problem, if I have 2 env variables how can I define them with `--define` flag

**Comment by rschristian** [comment] 2024-05-17 04:25
Use a comma to separate them, e.g.:

`$ microbundle --define process.env.MY_VAR="hello world!",foo="bar"`

**Comment by yenle16** [comment] 2024-05-17 04:34
`    "dev": "microbundle watch --no-sourcemap --external none --define process.env.PREACT_APP_API_URL='xxx',process.env.PREACT_APP_DOMAIN_URL ='yyy'",`
i tried it before with this script

**Comment by rschristian** [comment] 2024-05-17 06:00
I can't reproduce, that works just fine for me.

**Comment by yenle16** [comment] 2024-05-17 06:42
Many thanks for helping me, I did it

**Comment by rschristian** [comment] 2024-05-17 06:44
I'll close this out in that case, but feel free to reply here or open a new issue if you continue to have any problems.

**Closed by rschristian** 2024-05-17 06:44 UTC
