### ISSUE TITLE
o/p files not getting generated in different (linux) environment

### ISSUE THREAD

**Issue by yashhy** [developit/microbundle#316] opened 2019-02-14 13:36 UTC
I'm trying to build one file using microbundle using the following command

`microbundle build -i=app/index.js -o=dist/index.js -f=iife --sourcemap=false`

in my local machine the `index.js`is getting generated and can see the generated file (`index.js`) in dist folder but in a CI CD deployer instances the file isn't even getting generated.

Have attached screenshots for reference 

**Expected : (working in local machine)** 
```
root
|_ app
   |_ index.js (file to be minified)
|_ dist
   |_ index.js  (o/p file after minification)
```

**Result : (as seen in deployer instance)**
```
root
|_ app
   |_ index.js (file to be minified
|_ dist
   |_   (empty folder after running microbundle)
```

Local Machine OP : 
<img width="940" alt="mac" src="https://user-images.githubusercontent.com/4756393/52789958-566bbf00-308b-11e9-8617-144f827d486d.png">

Deployer Instance OP:
<img width="884" alt="linux" src="https://user-images.githubusercontent.com/4756393/52789968-5ff52700-308b-11e9-940a-85e4eabf9b5e.png">

Node Version : 8.11.0
Microbundle Version : 0.9.0

Local Machine Config: 
macOS Mojave
10.14.2

Deployer Instance Config: 
Ubuntu
18.04.2 LTS

**Comment by developit** [comment] 2019-02-23 22:32
Is it possible you're using different shells on these machines?

**Comment by yashhy** [comment] 2019-02-25 05:33
@developit just verified, both uses `bash`

**Comment by developit** [comment] 2019-02-25 19:00
Some things to try: `build` is the default, and `-i` is an alias for ordered arguments. Maybe try this?

```sh
microbundle app/index.js -o dist/index.js -f iife --no-sourcemap
```

**Comment by yashhy** [comment] 2019-03-05 06:14
@developit tried the above command in Ubuntu and it worked!

However I didn't understand your comment on `-i` being an ordered arguments. 

In docs it says `-i, --entry      Entry module(s)` I'm I missing something here?

**Comment by andyrichardson** [comment] 2019-06-08 11:58
Can confirm this is an issue. I've been experiencing the same problem and I suspect it could be related to storage drivers.

I am able to execute a microbundle build successfully in the `node:12` docker image locally on my machine. In the exact same image on GitLab, there is no build output (just an empty folder) despite an exit code of 0.

You can find the [failing CI here](https://gitlab.com/andyrichardson/tipple/-/jobs/227696278) and the [CI config here](https://github.com/andyrichardson/tipple/blob/master/.gitlab-ci.yml#L32).

I'll experiment with some docker storage drivers and see if I can reproduce the failure locally.

**Comment by sergonius** [comment] 2019-07-03 11:07
Came here to chime in that indeed there is something silently not working.

When using Gitlab CI, everything seems to run fine but the output is not generated.
Locally, everything works as expected.

Any tips on how to debug this or otherwise provide useful information towards resolving the issue?

**Comment by developit** [comment] 2020-12-18 21:26
Closing since we've upgraded almost every dependency that could have caused this since the issue was last discussed. Please re-open if you're still having issues.

**Closed by developit** 2020-12-18 21:26 UTC
Labels: bug :bug:, help wanted :wave:, question :grey_question:
