### ISSUE TITLE
Wrong modern output

### ISSUE THREAD

**Issue by jnordberg** [developit/microbundle#582] opened 2020-04-04 14:21 UTC
When running `microbundle --compress false --format modern` on a typescript package containing async/await code the js still contains the async/await calls but when running with `microbundle --compress false --format cjs,modern` both the modern and commonjs bundle have the async calls converted to promises

**Comment by jnordberg** [comment] 2020-04-04 14:21
Using 0.12.0-next.8

**Comment by developit** [comment] 2020-04-05 00:16
This should be fixed by #570. I'll work on getting a release out this week.

**Comment by developit** [comment] 2020-04-10 15:40
Note: this is a duplicate of #518 and #560.

**Comment by marvinhagemeister** [comment] 2020-05-30 18:47
Let's continue discussion in #518 and #560 .

**Closed by marvinhagemeister** 2020-05-30 18:47 UTC
Labels: duplicate, has-fix
