### ISSUE TITLE
[TS] Generators not working

### ISSUE THREAD

**Issue by phryneas** [developit/microbundle#319] opened 2019-02-18 08:48 UTC
It seems that (at least in my Typescript project), Generators are not correctly transpiled before buble, which does not support generators.

(buble plugin) CompileError: Generators are not supported (12:2)

**Comment by developit** [comment] 2019-02-23 22:29
We'll want to handle these in Babel. This actually might require dropping Bublé entirely.

**Comment by zzswang** [comment] 2019-06-29 07:38
Do we support generators now?

want to build module with redux-saga...

**Comment by jamiekyle-eb** [comment] 2019-07-11 00:11
I would really like to ship a library with generators untranspiled. @developit Is there any way that I can pass options to bublé?

**Comment by cowboyd** [comment] 2019-11-25 23:38
Generators appear to work with `microbundle@next`, but I can't seem to ship them untranspiled :/

**Comment by bryik** [comment] 2019-12-02 22:30
No error is thrown when bundling code containing async generators. 

Also if you have an async generator inside a class, its `this` reference is broken (points to `Window`). Could be my fault, but the code I was trying to bundle works fine unbundled ([example repl](https://repl.it/@bryik/generator-context)).

**Comment by MarkLyck** [comment] 2020-03-02 19:49
Running into this problem too. But it doesn't seem to be fixed in microbundle@next

`(buble plugin) CompileError: Transforming generators is not implemented. Use `transforms: { generator: false }` to skip transformation and disable this error. (237:33)`

This is happening in a third party module so I can't even opt to not use a generator in this case.

**Comment by ForsakenHarmony** [comment] 2020-03-03 10:09
@MarkLyck that error is from microbundle@latest?

**Comment by MarkLyck** [comment] 2020-03-03 17:28
@ForsakenHarmony Yeah both in @latest and @next as far as I can tell.

**Comment by ForsakenHarmony** [comment] 2020-03-03 23:02
We don't have buble in @next, are you sure you don't use a global install or something?

**Comment by MarkLyck** [comment] 2020-07-03 18:48
Any updates on this? @developit

**Comment by wardpeet** [comment] 2020-07-04 19:05
Hi @MarkLyck !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

**Comment by ForsakenHarmony** [comment] 2020-07-21 01:48
Gonna close this for now, leave a comment if it's still an issue with v0.12

**Closed by ForsakenHarmony** 2020-07-21 01:48 UTC
Labels: bug :bug:, enhancement :rocket:, help wanted :wave:
